param(
    # CSV generated by setPermissions.ps1
    [string]$CsvPath = "C:\Scripts\DeptResponsables.csv",

    # Base shares root (matches FSRMconf.ps1)
    [string]$SharesRoot = "C:\Shares",

    # Sizes from the spec
    [int]$DeptQuotaMB = 500,
    [int]$SubDeptQuotaMB = 100
)

Import-Module FileServerResourceManager -ErrorAction Stop

Write-Host "== Mise à jour des quotas FSRM par responsable (mode simple) ==" -ForegroundColor Cyan

# CSV: Department,SubDept,ManagerSam,ManagerMail
$csv = Import-Csv "$($CsvPath)"

function New-RespThresholds {
    param(
        [string] $MailTo
    )

    # 80% : mail only
    $act80 = New-FsrmAction -Type Email -MailTo $MailTo
    $th80 = New-FsrmQuotaThreshold -Percentage 80 -Action $act80

    # 90% : mail + event
    $act90 = @(
        New-FsrmAction -Type Email -MailTo $MailTo
        New-FsrmAction -Type Event
    )
    $th90 = New-FsrmQuotaThreshold -Percentage 90 -Action $act90

    # 100% : mail + event
    $act100 = @(
        New-FsrmAction -Type Email -MailTo $MailTo
        New-FsrmAction -Type Event
    )
    $th100 = New-FsrmQuotaThreshold -Percentage 100 -Action $act100

    return @($th80, $th90, $th100)
}

foreach ($row in $csv) {
    $dept = $row.Department
    $sub = $row.SubDept
    $mail = $row.ManagerMail

    $path = "C:\Shares\$dept\$sub"

    $quota = Get-FsrmQuota -Path $path -ErrorAction SilentlyContinue
    if (-not $quota) {
        Write-Warning "Pas de quota existant pour $path, on saute."
        continue
    }

    $size = [int64]$quota.Size  # bytes

    Write-Host "[*] $path -> MailTo: $mail ; Size: $($size/1MB) MB" -ForegroundColor Green

    # Recrée les seuils pour ce responsable
    $thresholds = New-RespThresholds -MailTo $mail

    # Supprime le quota existant
    Remove-FsrmQuota -Path $path -Confirm:$false -ErrorAction SilentlyContinue

    # Recrée un quota « hard » avec les nouveaux seuils
    New-FsrmQuota `
        -Path      $path `
        -Size      $size `
        -SoftLimit:$false `
        -Threshold $thresholds `
        -Description "Quota avec responsable $mail" `
        -ErrorAction Stop | Out-Null
}

Write-Host "== Mise à jour des quotas FSRM terminée ==" -ForegroundColor Cyan
